# Site wide config
source          : source
destination     : prod

title           : "Jason Heppler"
description     : 'Historian. Librarian. Technologist.'
tagline         : "History, technology, design"
url             : "https://jasonheppler.org"
base            : ""
repository      : "http://github.com/hepplerj/hepplerj.github.com"
timeline        : America/Chicago

# Jekyll configuration
multivews       : true
plugins_dir     : plugins
lsi             : false
future          : false
show_drafts     : false
markdown        : kramdown
kramdown:
  toc_levels    : 1..3
  input         : GFM
  hard_wrap     : false
  auto_ids      : true
  entity_output : as_char
permalink       : /:year/:month/:day/:title/
highlighter     : rouge

# Site owner
owner:
  name: Jason Heppler
  email: jason@jasonheppler.org
  vita: https://www.dropbox.com/s/cpbo7md7dooffg1/jah-cv.pdf?dl=0 
  twitter: jaheppler
  instagram: "hepplerj"
  github: "hepplerj"
  facebook: "jason.heppler"
  linkedin: "jasonheppler"
  google_analytics: UA-12786552-1
  google_plus: http://plus.google.com/112447146120355094986
  bing_verify: D81F4C18A6CB3018F64D7C827D953DFD

  bio: "Historian of the North American West, environmental and urban history, digital history, coffee hobbyist"
  avatar: avatar.jpg

google_analytics_tracking_id: UA-12786552-1

# Settings
#assets:
#  compress:
#    css: true
#    js: true
#  features:
#    automatic_img_size: false
#  sources:
#    - assets/fonts
#    - assets/images
#    - assets/javascripts
#    - assets/stylesheets

# Navigation
links:
  - title: About
    url: /about/
  - title: Archives
    url: /archives/
  - title: Research
    url: /research/
  - title: Speaking
    url: /speaking/
  - title: Teaching
    url: /teaching/

exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - export.xml
  - Gemfile
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Plugin settings
feed:
  path: source/feed.xml

figures:
  dir: /figures
  enumerate: true
  analytics: true

# Course information
course_baseurl: "/teaching/hist205f.2014"
course_url: "http://jasonheppler.org/teaching/hist205f.2014"
course_pdf: http://stanford.edu/~jheppler/stanford.syllabus.hist205f.2014f.pdf
course_title: "Digital History: Sources, Methods, Problems"
course_credithours: 5
course_hashtag: hist205f
course_meetingtime: "Mon., 3:15&ndash;6:05 p.m."
course_number: "HISTORY 205F"
course_prerequisites: "None"
course_room: "Wallenberg 326"
course_semester: "Fall 2014"
instructor_email: jheppler@stanford.edu
instructor_name: Jason Heppler
instructor_office: "Lane Rm. 122"
instructor_officehours: "Mon., 9a--11a, and Thurs., 10a--12p, or by appointment"
instructor_officehours_link: http://jasonheppler.org/officehours
instructor_twitter: jaheppler
instructor_website: http://jasonheppler.org
course_description: "An introduction to digital history."
