# Dependencies
multivews:      true
source:         source
destination:    _site
highlighter:    pygments
markdown:       kramdown
# http://jekyllrb.com/docs/permalinks/
permalink:      /:year/:month/:day/:title/

# Setup
title:            Jason Heppler
tagline:          "History, technology, coffee"
description:      'Historian of the American West.'
url:

# Site owner
owner:
  name: Jason Heppler
  email: jason@jasonheppler.org
  vita: /downloads/pdf/jah-vita.pdf
  twitter: jaheppler
  instagram: "hepplerj"
  github: "hepplerj"
  facebook: "jason.heppler"
  google:
    analytics: UA-12786552-1
    plus: http://plus.google.com/112447146120355094986
  bing:
    verify: D81F4C18A6CB3018F64D7C827D953DFD

  bio: "Historian of the North American West, environmental and urban history, digital history, coffee hobbyist"
  avatar: avatar.jpg

# Course information
course_baseurl: "/teaching/hist205f.2014"
course_url: "http://jasonheppler.org/teaching/hist205f.2014"
course_pdf: http://stanford.edu/~jheppler/stanford.syllabus.hist205f.2014f.pdf
course_title: "Digital History: Sources, Methods, Problems"
course_credithours: 5
course_hashtag: hist205f
course_meetingtime: "Mon., 3:15&ndash;6:05 p.m."
course_number: "HISTORY 205F"
course_prerequisites: "None"
course_room: "Wallenberg 326"
course_semester: "Fall 2014"
instructor_email: jheppler@stanford.edu
instructor_name: Jason Heppler
instructor_office: "Lane Rm. 122"
instructor_officehours: "Mon., 9a--11a, and Thurs., 10a--12p, or by appointment"
instructor_officehours_link: http://jasonheppler.org/officehours
instructor_twitter: jaheppler
instructor_website: http://jasonheppler.org
course_description: "An introduction to digital history."

# paginate:         10

figures:
  dir: /figures
  enumerate: true
  analytics: true

links:
  - title: Home
    url: /
  - title: Archives
    url: /archives/
  - title: "Digital & Public History"
    url: /digital/
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/

google_analytics_tracking_id: UA-12786552-1

gems:
    - jekyll-feed
