name: Jason Heppler
description: History, Technology, Coffee
meta_description: "Jason Heppler's blog"

markdown: kramdown
pygments: true
logo: false
paginate: 15
permalink:      /:year/:month/:day/:title.html

# Details for the RSS feed generator
url:            'http://jasonheppler.org'
author:         'Jason Heppler'
