name: Jason Heppler
description: Historian, writer, geek, and coffee enthusiast 
meta_description: "The online home of Jason Heppler"

markdown: kramdown
pygments: true
logo: false
paginate: 15
permalink:      /:year/:month/:day/:title.html

# Details for the RSS feed generator
url:            'http://jasonheppler.org'
author:         'Jason Heppler'
