multivews: true

source:         .
destination:    ./_site
includes:       ./_includes

pygments:       true
markdown:       kramdown
permalink:      /:year/:month/:day/:title.html

name:	          JasonHeppler.org
base_url:       http://jasonheppler.org
description:    "A blog covering digital history, the U.S. West, environmental and urban history, and sometimes coffee"
root_desc:      "JasonHeppler.org"

exclude: ['Rakefile', 'README.markdown', 'config.rb']
