# Dependencies
multivews:      true
source:         .
highlighter:    pygments
markdown:       kramdown
# http://jekyllrb.com/docs/permalinks/
permalink:      /:year/:month/:day/:title/

# Setup
title:            Jason Heppler
tagline:          "History, technology, coffee"
description:      'Historian of the American West.'
url:              http://jasonheppler.org

# Owner/author information
owner:
  name:           Jason Heppler
  avatar:         avatar.jpg
  bio:            "Historian of the North American West, environmental and urban history, digital history, coffee hobbyist"
  email:          jason@jasonheppler.org
  twitter:        "jaheppler"
  instagram:      "hepplerj"
  github:         "hepplerj"
  facebook:       "jason.heppler"
  vita:           https://www.dropbox.com/s/lbre2593encazi3/jah-vita.pdf
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "http://plus.google.com/112447146120355094986"


paginate:         5

figures:
  dir: /figures
  enumerate: true
  analytics: true

github:
  repo:           https://github.com/hepplerj

google_analytics_tracking_id: UA-12786552-1
