title = "Jason A. Heppler"
description = "Jason Heppler is the senior web developer at the Roy Rosenzweig Center for History and New Media at George Mason University."
baseURL = "https://jasonheppler.org/"
copyright = "2008-2021"
languageCode = "en-us"
footnoteReturnLinkContents = "&#8593;"

[permalinks]
  blog = "/:year/:month/:day/:slug/"
  archive = "/:slug/"
  page = "/:section/:slug/"

disableKinds = "taxonomyTerm"

assetDir = "static"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

[author]
  name = "Jason Heppler"
  email = "jason@jasonheppler.org"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[markup]
  defaultMarkdownHandler = "blackFriday"
  [markup.highlight]
    guessSyntax = true
    style = 'vc'

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[services.rss]
  limit = 20