title: "Jason A. Heppler"
description: "Jason Heppler is a historian of American environmentalism and the twentieth-century United States."
baseURL: "https://jasonheppler.org/"
copyright: "2008-2019"
languageCode: "en-us"

permalinks:
  blog: "/:year/:month/:day/:slug/"
  archive: "/:slug/"
  page: "/:section/:slug/"

blackfriday:
  fractions: false

pygmentsCodefences: true
pygmentsUseClasses: true

params:
  blogFeedTitle: "Jason Heppler's blog"

taxonomies: false

author:
  name: "Jason Heppler"
  email: "jason@jasonheppler.org"

outputs:
  home: ["HTML","RSS"]

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"