title: "Jason A. Heppler"
description: "Jason Heppler is a historian of the American environment and the twentieth-century United States."
baseURL: "https://jasonheppler.org/"
copyright: "2008-2020"
languageCode: "en-us"

permalinks:
  blog: "/:year/:month/:day/:slug/"
  archive: "/:slug/"
  page: "/:section/:slug/"

markup: 
  defaultMarkdownHandler: blackFriday
  blackfriday:
    fractions: false
  highlight:
    style: vs

pygmentsCodefences: true
pygmentsUseClasses: true

params:
  blogFeedTitle: "Jason Heppler's blog"

taxonomies: false

assetDir: "static"

author:
  name: "Jason Heppler"
  email: "jason@jasonheppler.org"

outputs:
  home: ["HTML","RSS"]

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"
